title: Ramblings
author: Abhishek Kumar
email: abhishekkumar8222@gmail.com
description: A personal website by me, Abhishek. I ramble about my life and the lessons learnt. Hang tight for the ride!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhishekkumar2718.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  abhishekkumar2718

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

posts_offset: 0

sass:
  sass_dir: assets/css

social_links:
  github: abhishekkumar2718
  instagram: abhishek_kumar2718

date_format: '%b %-d, %Y'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - todo.yml

algolia:
  application_id: SQBFJ93CTL
  index_name: prod_master
  search_only_api_key: dcd07f3c3fd1edcb95aea61abbea42d1
